version : '3.9'

services:
    api:
        build: ./api/
        hostname: api
        environment:
         - API_PORT=${API_PORT}
        volumes:
          - ./api/code:/app
        ports:
          - ${API_PORT}:${API_PORT}
    consumer:
        build: ./consumer/
        hostname: consumer
        environment:
          - API_HOST=${API_HOST}   
          - API_PORT=${API_PORT}   
          - API_ENDPOINT=${API_ENDPOINT} 
          - CONSUMER_PORT=${CONSUMER_PORT}  
        #command: python consumer.py 
        volumes:
          - ./consumer/code:/app
        ports:
          - ${CONSUMER_PORT}:${CONSUMER_PORT}