version : '3.9'

services:

    api:
        build: ./api/
        hostname: api
        environment:
          - API_PORT=${API_PORT}
        volumes:
          - ./api/code:/app
        ports:
          #- "5002:5002"
          - "0.0.0.0:${API_PORT}:${API_PORT}"
    consumer:
        build: ./consumer/
        hostname: consumer
        environment:
          - CONSUMER_PORT = ${CONSUMER_PORT}
        volumes:
          - ./consumer/code:/app
        ports:
           - "0.0.0.0:${CONSUMER_PORT}:${CONSUMER_PORT}"