version: '3.9'
services:
  api:
    build: ./api/
    hostname: ${API_HOST}
    environment:
      - API_PORT=${API_PORT}
      - DBHOST=${DB_HOST}
    command: python api.py
    volumes:
      - ./api/code:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env

  consumer: 
    build: ./consumer/
    hostname: consumer
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - CONSUMER_PORT=${CONSUMER_PORT}
    command: python consumer.py 
    volumes:
      - ./consumer/code:/app
    ports:
      - "${CONSUMER_PORT}:${CONSUMER_PORT}"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d  
    ports:
      - "${PG_PORT}:${PG_PORT}"

  dba:
    image: dpage/pgadmin4
    hostname: dba
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_NAME}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}
    volumes:
      - pga:/var/lib/pga
    ports:
      - "${PG_ADMIN_PORT}:80"

volumes:
    pga: